name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - run: sudo apt-get install ninja-build
    - uses: actions/checkout@v1
    - name: build
      run: mkdir build && cd build && cmake -G Ninja ../
      run: ninja
